### ISSUE TITLE
关于Air Play 碰到的几个问题

### ISSUE THREAD

**Issue by zhudongyong** [binarysai/AirplayMirror#1]
1、iOS 设备进入待机后，再重新唤起后，Airplay的连接不能自动恢复;
2、只能同时连接一台AirPlay设备;

**Comment by binarysai** [comment]
i fix the first issue 
in most cases,  one device is reasonable, so no plan to support multi devices

**Comment by zhudongyong** [comment]
Can I ask you how to decrypt the FairPlay DRM of AirMirror?
